POST http://localhost:3000/api/services
Content-Type: application/json

{
  "name": "Ballpool",
  "description": "A pool with 3,000 colorful balls for everyone to enjoy.",
  "price": 1500,
  "image": "https://vejario.abril.com.br/wp-content/uploads/2018/01/piscina-de-bolinhas-smb.jpeg?crop=1&resize=1212,909"
}

###
GET http://localhost:3000/api/services

###

GET http://localhost:3000/api/services/692c2e755c1c2e778f016a22

###

DELETE http://localhost:3000/api/services/692c2e755c1c2e778f016a22

###

PUT http://localhost:3000/api/services/692c2e755c1c2e778f016a22
Content-Type: application/json

{
  "name": "TESTE ATUALIZACAO",
  "description": "A pool with 3,000 colorful balls for everyone to enjoy.",
  "price": 130,
  "image": "https://vejario.abril.com.br/wp-content/uploads/2018/01/piscina-de-bolinhas-smb.jpeg?crop=1&resize=1212,909"
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
  "title": "Meu evento",
  "author": "Leonardo",
  "description": "Uma festa marota",
  "budget": 2000,
  "image": "https://vejario.abril.com.br/wp-content/uploads/2018/01/piscina-de-bolinhas-smb.jpeg?crop=1&resize=1212,909",
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
  "title": "Meu evento",
  "author": "Leonardo",
  "description": "Uma festa marota",
  "budget": 4200,
  "image": "https://i.pinimg.com/736x/ab/d7/02/abd702bd6c609f2d4595efe6bde11b4b.jpg",
  "services": [
    {
    "name": "Ballpool",
    "description": "A pool with 3,000 colorful balls for everyone to enjoy.",
    "price": 1500,
    "image": "https://vejario.abril.com.br/wp-content/uploads/2018/01/piscina-de-bolinhas-smb.jpeg?crop=1&resize=1212,909"
    },
    {
      "name": "Cotton Candy",
      "description": "Cotton candy to everybody it was cool.",
      "price": 800,
      "image": "https://cdn.hswstatic.com/gif/cotton-candy-57337230.jpg"
    }
  ]
}

### 
GET http://localhost:3000/api/parties

### 
GET http://localhost:3000/api/parties/692c4c03063e23d3c5000719

### 
DELETE http://localhost:3000/api/parties/692c4c03063e23d3c5000719

### 
PUT http://localhost:3000/api/parties/692c4c03063e23d3c5000719
Content-Type: application/json

{
  "title": "Meu evento",
  "author": "Leonardo",
  "description": "Uma festa marota",
  "budget": 2000,
  "image": "https://vejario.abril.com.br/wp-content/uploads/2018/01/piscina-de-bolinhas-smb.jpeg?crop=1&resize=1212,909",
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
  "title": "Meu evento 2",
  "author": "Leonardo",
  "description": "Uma festa marota",
  "budget": 4200,
  "image": "https://i.pinimg.com/736x/ab/d7/02/abd702bd6c609f2d4595efe6bde11b4b.jpg",
  "services": [
    {
    "name": "Ballpool",
    "description": "A pool with 3,000 colorful balls for everyone to enjoy.",
    "price": 1500,
    "image": "https://vejario.abril.com.br/wp-content/uploads/2018/01/piscina-de-bolinhas-smb.jpeg?crop=1&resize=1212,909"
    },
    {
      "name": "Cotton Candy",
      "description": "Cotton candy to everybody it was cool.",
      "price": 800,
      "image": "https://cdn.hswstatic.com/gif/cotton-candy-57337230.jpg"
    }
  ]
}